server:
  port: 1001
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fhadmin_a?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
